basePath: /
definitions:
  main.Album:
    description: album information with album id, album title, arist and price
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: roberto140298@gmail.com
    name: Roberto Guzmán
  description: Simple Swagger implementations in GO HTTP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Albums RESTful API with Swagger
  version: "0.1"
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: get albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Album'
            type: array
      summary: List albums
      tags:
      - album
    post:
      consumes:
      - application/json
      parameters:
      - description: Album JSON Object
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/main.Album'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/main.Album'
        "400":
          description: BadRequest
          schema:
            type: string
      summary: Create a new album
      tags:
      - album
  /albums/{id}:
    get:
      consumes:
      - application/json
      description: Get a single album from the database corresponding to the id in
        the path. Otherwise, returns error
      parameters:
      - description: Album Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Album'
        "404":
          description: NotFound
          schema:
            type: string
      summary: Get an album
      tags:
      - album
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
